import React, { useState } from 'react';
import '../styles/IgnouBcaMcaLanding.css';

const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';
const WHATSAPP_URL = 'https://wa.me/918630611232?text=Hi%20AILYT%2C%20I%20want%20to%20know%20about%20IGNOU%20BCA%2FMCA%20support.';

const chips = ['Semester-Wise Support', 'Programming Practice', 'Live Projects', 'Industrial Training', 'Assignment Guidance', 'PYQ Preparation', 'Portfolio Development', 'Career Preparation'];
const painPoints = ['Difficult to understand some subjects independently', 'Programming feels confusing without guided practice', 'No regular study routine', 'Assignment deadlines become stressful', 'Practical and lab work needs guidance', 'Unsure what to prepare before exams', 'No project portfolio by final year', 'Resume still looks empty near graduation', 'No exposure to industrial training', 'Not sure how concepts connect to jobs'];
const supportCards = [
  ['01', 'Semester-Wise Academic Support', 'Clarify current IGNOU concepts, plan the semester, and revise with structured guidance.'],
  ['02', 'Programming Practice', 'Build logic through guided coding, exercises, debugging, and regular lab practice.'],
  ['03', 'Practical / Lab Guidance', 'Work through demonstrations, practical files, viva preparation, and hands-on tasks.'],
  ['04', 'Assignment Guidance', 'Understand questions, structure your own answers, improve presentation, and plan submissions.'],
  ['05', 'PYQ + Exam Preparation', 'Map important topics, practise previous-year questions, revise, and develop exam-writing strategy.'],
  ['06', 'Live Projects', 'Turn concepts into small, functional, and progressively more professional projects.'],
  ['07', 'Industrial Training', 'Experience briefs, task planning, Git workflows, reviews, documentation, and presentations.'],
  ['08', 'Career & Portfolio Development', 'Grow your GitHub, resume, LinkedIn, interview confidence, and project presentation skills.'],
];
const journey = [
  ['YEAR 1', 'FOUNDATION', ['Computer fundamentals', 'Programming logic', 'Basic practical work', 'Digital productivity', 'Mini projects', 'First GitHub exposure']],
  ['YEAR 2', 'APPLICATION & PROJECT DEVELOPMENT', ['Databases and SQL', 'Data structures', 'Web and application development', 'APIs and Git/GitHub', 'Live projects', 'Industrial training exposure']],
  ['YEAR 3', 'PROFESSIONAL & CAREER READINESS', ['Advanced practical skills', 'Analytics or data tools where relevant', 'Capstone development', 'Industrial training', 'Portfolio and resume', 'LinkedIn and mock interviews']],
];
const semesterSupport = [
  ['SEMESTER 1', 'FOUNDATION', ['Current IGNOU concepts, topic clarification, semester planning, assignments, PYQs, revision', 'Programming logic, coding exercises, basic debugging, computer productivity', 'Small logic programs and a beginner mini project', 'Technical learning habits, basic communication, portfolio thinking']],
  ['SEMESTER 2', 'PROGRAMMING + DATA FOUNDATION', ['Current semester support, assignments, PYQs, and revision planning', 'Stronger programming, arrays, functions, files, databases, Excel/data handling', 'Student record system, expense tracker, or inventory mini project', 'Create GitHub, upload selected work, and write a basic README']],
  ['SEMESTER 3', 'DATABASES + CORE APPLICATION SKILLS', ['Concept clarification and exam preparation for the current semester', 'SQL, DBMS, CRUD, joins, queries, data structures, algorithms', 'Database-backed student, inventory, or management application', 'Professional workflow, version control, task-based work, code review habits']],
  ['SEMESTER 4', 'WEB / APPLICATION DEVELOPMENT', ['Academic support, assignments, PYQs, and revision', 'HTML, CSS, JavaScript, APIs, JSON, responsive development, database integration', 'Business website, interactive JavaScript application, or application project', 'Team simulation, requirements, testing, task assignment, documentation']],
  ['SEMESTER 5', 'ADVANCED PRACTICAL + DATA / BUSINESS SKILLS', ['Current semester support and exam-focused revision', 'Python, SQL analytics, Excel, Power BI, data handling, business reporting where relevant', 'Business dashboard, Python analysis, SQL analysis, or applied technical project', 'Business problem, milestones, mentor review, documentation, presentation']],
  ['SEMESTER 6', 'CAPSTONE + CAREER PREPARATION', ['Final semester planning, assignments, PYQs, revision, and academic guidance', 'Final project, debugging, documentation, deployment or presentation where appropriate', 'Final industrial training project, report, mentor review, and presentation', 'Resume, LinkedIn, GitHub, interviews, project presentation, job-search readiness']],
];
const projects = [
  ['YEAR 1', 'Mini Projects', 'Logic programs, calculator, student record program, expense tracker'],
  ['YEAR 2', 'Functional Projects', 'Database management system, web application, interactive website, API-based application'],
  ['YEAR 3', 'Professional Projects', 'Python/data project, dashboard, business analysis, multi-tool application, capstone'],
];
const faqs = [
  ['Is AILYT part of IGNOU?', 'No. IGNOU governs the official curriculum, examinations, academic requirements, and degree. AILYT is an independent support partner.'],
  ['Does AILYT replace the IGNOU curriculum?', 'No. The AILYT Professional Learning Track runs alongside your current IGNOU curriculum and adds practical and career development support.'],
  ['Will you teach my current semester subjects?', 'AILYT can support understanding, planning, assignments, PYQs, revision, and practical work for your current semester. Confirm the exact batch coverage during counselling.'],
  ['Do you provide practical programming classes?', 'Yes. Programming practice, lab exercises, debugging, practical files, and mentor review are part of the support plan where applicable.'],
  ['Are live projects included?', 'The track is designed to build projects progressively each year. Confirm the current batch structure and project schedule with AILYT.'],
  ['What does industrial training mean?', 'It means guided exposure to professional workflows, project briefs, task planning, Git/GitHub, documentation, reviews, presentations, and mentor feedback. It is not a claim of employment.'],
  ['When does industrial training begin?', 'Exposure begins progressively through project work and becomes more structured as your skills develop. The exact schedule depends on the current track.'],
  ['Will I build a GitHub portfolio?', 'The intended progression is to create GitHub in Semester 2, add projects from Semester 3 onward, and polish repositories with your capstone in Semester 6.'],
  ['Will you help with assignments?', 'Yes, with question understanding, concept identification, structure, presentation, timelines, and review of student-created work. AILYT does not provide completed assignments.'],
  ['Do you cover PYQs and labs?', 'Yes, topic-wise PYQs, revision planning, mock practice, lab guidance, practical revision, and viva preparation are included where applicable.'],
  ['Can existing BCA students join midway?', 'Yes, existing students can discuss their semester, current skills, and goals during counselling to identify a suitable entry point.'],
  ['Do you support MCA and working students?', 'Yes. MCA support follows the same academic, practical, project, industrial training, portfolio, and career preparation philosophy. Working students can discuss schedule options.'],
  ['Do you guarantee placement, salary, or marks?', 'No. AILYT provides skill development and career preparation. There is no guarantee of placement, salary, marks, or employment.'],
];

const initialForm = { firstName: '', lastName: '', phone: '', email: '', city: '', program: '', semester: '', support: '', mode: '', message: '', consent: false };
const supportOptions = ['Full Semester Support', 'Programming', 'Practicals / Labs', 'Assignments', 'PYQs / Exam Preparation', 'Live Projects', 'Industrial Training', 'Portfolio / Resume', 'Career Guidance', 'Other'];

function EnquiryModal({ type, onClose }) {
  const [form, setForm] = useState(initialForm);
  const [status, setStatus] = useState({ loading: false, error: '', success: '' });
  const update = (event) => { const { name, value, type: inputType, checked } = event.target; setForm((previous) => ({ ...previous, [name]: inputType === 'checkbox' ? checked : value })); setStatus({ loading: false, error: '', success: '' }); };
  const submit = async (event) => {
    event.preventDefault();
    if (!form.firstName || !form.lastName || !form.phone || !form.email || !form.program || !form.semester || !form.support || !form.mode || !form.message || !form.consent) { setStatus({ loading: false, error: 'Please complete all required fields and consent to contact.', success: '' }); return; }
    setStatus({ loading: true, error: '', success: '' });
    const leadType = type === 'guide' ? (form.program === 'MCA' ? 'ignou-mca-program-guide' : 'ignou-bca-program-guide') : (form.program === 'MCA' ? 'ignou-mca-counselling' : 'ignou-bca-counselling');
    const payload = { fullName: `${form.firstName} ${form.lastName}`, phone: form.phone, email: form.email, courseInterest: leadType, learningMode: form.mode, startPlan: 'just-exploring', qualification: `${form.program}, ${form.semester}, ${form.city}`, message: `Main support needed: ${form.support}. ${form.message}`, consent: form.consent };
    try {
      const response = await fetch(`${API_BASE_URL}/enquiries`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
      const result = await response.json().catch(() => ({}));
      if (!response.ok) throw new Error(result.message || 'Unable to submit your enquiry.');
      setStatus({ loading: false, error: '', success: 'Thank you. Your enquiry was submitted successfully.' });
      if (type === 'guide') window.open('/downloads/ignou-bca-mca-program-guide.txt', '_blank', 'noopener,noreferrer');
      setForm(initialForm);
    } catch (error) { setStatus({ loading: false, error: error.message || 'Unable to submit your enquiry right now.', success: '' }); }
  };
  return <div className="ignou-modal-backdrop" role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="ignou-modal" role="dialog" aria-modal="true" aria-labelledby="ignou-modal-title"><button className="ignou-close" type="button" onClick={onClose} aria-label="Close enquiry form">×</button><p className="ignou-kicker">AILYT LEARNING CENTRE</p><h2 id="ignou-modal-title">{type === 'guide' ? 'Get the IGNOU support guide' : 'Book free counselling'}</h2><p className="ignou-modal-intro">Share your current stage and the support you need. AILYT will contact you with current batch details.</p><form onSubmit={submit}><div className="ignou-form-grid"><label>First Name *<input name="firstName" value={form.firstName} onChange={update} required /></label><label>Last Name *<input name="lastName" value={form.lastName} onChange={update} required /></label><label>Phone *<input name="phone" type="tel" value={form.phone} onChange={update} required /></label><label>Email *<input name="email" type="email" value={form.email} onChange={update} required /></label><label>City *<input name="city" value={form.city} onChange={update} required /></label><label>Current Program *<select name="program" value={form.program} onChange={update} required><option value="">Select</option><option>BCA</option><option>MCA</option></select></label><label>Current Semester *<select name="semester" value={form.semester} onChange={update} required><option value="">Select</option>{['Semester 1', 'Semester 2', 'Semester 3', 'Semester 4', 'Semester 5', 'Semester 6', 'Not started'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Main Support Needed *<select name="support" value={form.support} onChange={update} required><option value="">Select</option>{supportOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label>Preferred Mode *<select name="mode" value={form.mode} onChange={update} required><option value="">Select</option><option value="classroom">Classroom</option><option value="hybrid">Hybrid</option><option value="online-support">Online + mentor support</option></select></label><label className="ignou-field-wide">Message *<textarea name="message" value={form.message} onChange={update} rows="4" required placeholder="Tell us what you want help with." /></label></div><label className="ignou-consent"><input type="checkbox" name="consent" checked={form.consent} onChange={update} /> I agree to be contacted by AILYT via phone, email, or WhatsApp about this enquiry.</label>{status.error && <p className="ignou-form-error" role="alert">{status.error}</p>}{status.success && <p className="ignou-form-success" role="status">{status.success}</p>}<button className="ignou-btn ignou-btn-primary ignou-submit" disabled={status.loading}>{status.loading ? 'Submitting...' : 'Submit Enquiry'}</button></form></section></div>;
}

const CTA = ({ children, onClick, outline = false }) => <button type="button" className={`ignou-btn ${outline ? 'ignou-btn-outline' : 'ignou-btn-primary'}`} onClick={onClick}>{children} <span aria-hidden="true">↗</span></button>;

function IgnouBcaMcaLanding() {
  const [modal, setModal] = useState(null);
  const [openFaq, setOpenFaq] = useState(null);
  const openCounselling = () => setModal('counselling');
  return <div className="ignou-landing" id="top">
    <header className="ignou-hero"><div className="ignou-wrap ignou-hero-grid"><div><p className="ignou-kicker">IGNOU BCA + MCA | AILYT PROFESSIONAL LEARNING TRACK</p><h1>Study IGNOU BCA/MCA with Practical Skills, Projects &amp; Industrial Training</h1><p className="ignou-lead">Your IGNOU degree gives you the academic foundation. AILYT helps you build the skills to use it through concept teaching, practical classes, programming practice, projects, portfolio work, and career preparation.</p><div className="ignou-chip-row">{chips.map((chip) => <span key={chip}>{chip}</span>)}</div><div className="ignou-actions"><CTA onClick={openCounselling}>Book Free Counselling</CTA><CTA onClick={() => setModal('guide')} outline>View Professional Learning Track</CTA><a className="ignou-btn ignou-whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer">Chat on WhatsApp ↗</a></div><p className="ignou-hero-note">Don't wait until final year to start preparing for your career.</p></div><div className="ignou-hero-board"><div className="ignou-board-top"><span>AILYT / IGNOU SUPPORT</span><b>● ● ●</b></div><div className="ignou-board-main"><span className="ignou-board-label">THE PROFESSIONAL LAYER</span><strong>Degree + Skills</strong><div className="ignou-board-stack"><span>Understand</span><span>Practise</span><span>Build</span><span>Present</span></div><small>Academic support alongside the official university curriculum</small></div></div></div></header>

    <main>
      <section className="ignou-section ignou-value"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">CLEAR ROLES, BETTER OUTCOMES</p><h2>IGNOU Gives You the Curriculum. AILYT Helps You Build the Experience.</h2><p>IGNOU provides the university curriculum, study material, examinations, and degree requirements. AILYT adds a structured professional layer with regular support, hands-on practice, live projects, industrial training, and career development.</p></div><div className="ignou-equation"><span>Degree</span><b>+</b><span>Practical Skills</span><b>+</b><span>Projects</span><b>+</b><span>Industrial Training</span><b>+</b><span>Portfolio</span><b>+</b><span>Career Preparation</span></div></div></section>
      <section className="ignou-section ignou-alt"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">FOR STUDENTS AT EVERY STAGE</p><h2>Does This Sound Familiar?</h2><p>These are common learning challenges. They are reasons to seek structure and guidance, not reasons to doubt your degree.</p></div><div className="ignou-pain-grid">{painPoints.map((item, index) => <article key={item}><span>0{index + 1}</span><p>{item}</p></article>)}</div></div></section>
      <section className="ignou-section"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">THE PROFESSIONAL SKILL LAYER</p><h2>How AILYT Supports You</h2></div><div className="ignou-support-grid">{supportCards.map(([number, title, text]) => <article className="ignou-card" key={title}><span className="ignou-number">{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="ignou-section ignou-alt" id="journey"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">ALONGSIDE YOUR CURRENT SEMESTER</p><h2>Three-Year BCA Professional Journey</h2><p>These stages describe AILYT's professional layer. They are not an official IGNOU subject list.</p></div><div className="ignou-journey-grid">{journey.map(([year, title, items]) => <article className="ignou-journey-card" key={year}><span>{year}</span><h3>{title}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div><div className="ignou-centered-cta"><CTA onClick={openCounselling}>Book Free Counselling</CTA></div></div></section>
      <section className="ignou-section" id="semesters"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">A SUPPORT PLAN THAT GROWS WITH YOU</p><h2>Semester-Wise Professional Support</h2></div><div className="ignou-semesters">{semesterSupport.map(([semester, title, layers]) => <article key={semester}><div className="ignou-semester-title"><span>{semester}</span><h3>{title}</h3></div><div className="ignou-layer-grid"><div><b>Academic Support</b><p>{layers[0]}</p></div><div><b>Practical / Programming</b><p>{layers[1]}</p></div><div><b>Project / Industrial Training</b><p>{layers[2]}</p></div><div><b>Career Development</b><p>{layers[3]}</p></div></div></article>)}</div></div></section>
      <section className="ignou-section ignou-alt"><div className="ignou-wrap ignou-two-col"><div><p className="ignou-kicker">PROGRESSIVE EXPOSURE</p><h2>Industrial Training Throughout the Learning Journey</h2><p>Industrial training at AILYT is designed to help students experience how technical work is planned, built, reviewed, and presented in a professional environment.</p><p>Students gradually gain exposure to professional workflows, project briefs, real or realistic business problems, teamwork, task planning, Git/GitHub, documentation, debugging, code reviews, presentations, mentor feedback, and milestone-based delivery.</p></div><div className="ignou-feature-panel"><span>INDUSTRIAL TRAINING</span><strong>Brief → Plan → Build → Review → Present</strong><small>Training is guided learning exposure. It does not represent employment or a placement promise.</small></div></div><div className="ignou-wrap ignou-centered-cta"><CTA onClick={openCounselling}>Discuss the Professional Track</CTA></div></section>
      <section className="ignou-section" id="projects"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">MAKE YOUR LEARNING VISIBLE</p><h2>Build Projects Every Year</h2></div><div className="ignou-project-grid">{projects.map(([year, title, text]) => <article key={year}><span>{year}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="ignou-section ignou-method ignou-alt"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">THE PRACTICAL LOOP</p><h2>Understand → Practise → Build → Review → Improve → Present</h2></div><div className="ignou-method-grid">{['Understand', 'Practise', 'Build', 'Review', 'Improve', 'Present'].map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>{['Connect concepts to your current semester.', 'Solve guided exercises in the lab.', 'Create work you can explain.', 'Get mentor feedback and corrections.', 'Refine code, documentation, and communication.', 'Show your project with confidence.'][index]}</p></article>)}</div></div></section>
      <section className="ignou-section"><div className="ignou-wrap ignou-two-col"><div><p className="ignou-kicker">SKILL CONFIDENCE</p><h2>Programming Becomes Easier When You Practise It</h2><p>AILYT supports logic building, guided coding, lab exercises, debugging, problem solving, practical files, mini projects, coding challenges, and mentor review.</p><h3 className="ignou-small-heading">Assignment guidance, not assignment completion</h3><p>Understand questions, identify concepts, structure your own answers, improve presentation, plan timelines, and review student-created work.</p></div><div className="ignou-list-panel"><h3>PYQ + Exam Preparation</h3><ul><li>Topic-wise previous-year questions</li><li>Repeated concepts and important-topic mapping</li><li>Revision planning and mock practice</li><li>Exam-writing strategy and semester revision</li><li>Practical, lab, and viva preparation</li></ul></div></div></section>
      <section className="ignou-section ignou-alt" id="portfolio"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">EVIDENCE OF WHAT YOU CAN BUILD</p><h2>Grow Your GitHub, Portfolio, Resume, and Career Readiness</h2><p>Instead of waiting until final year, build a technical profile alongside your degree.</p></div><div className="ignou-timeline"><div><span>SEM 2</span><strong>Create GitHub</strong></div><div><span>SEM 3</span><strong>Upload technical projects</strong></div><div><span>SEM 4</span><strong>Add web/application projects</strong></div><div><span>SEM 5</span><strong>Add advanced/live projects</strong></div><div><span>SEM 6</span><strong>Polish repositories + capstone</strong></div></div><div className="ignou-resume"><h3>Your Resume Should Grow with Your Degree</h3><p>Progressively add technical skills, projects, tools, GitHub links, industrial training, capstone work, presentations, and certifications where applicable. The goal is a stronger technical profile than a degree-only resume.</p><div className="ignou-tag-list">{['Resume preparation', 'LinkedIn profile', 'GitHub portfolio', 'Technical interviews', 'HR interview preparation', 'Mock interviews', 'Project presentation', 'Job search strategy'].map((item) => <span key={item}>{item}</span>)}</div></div></div></section>
      <section className="ignou-section"><div className="ignou-wrap ignou-two-col"><div><p className="ignou-kicker">BCA + MCA SUPPORT</p><h2>Academic Support + Practical Development + Career Preparation</h2><p>For MCA students, AILYT follows the same philosophy without inventing official subject names: support your current curriculum, strengthen practical development, build projects, gain industrial training exposure, and prepare your portfolio and career profile.</p></div><div className="ignou-tools"><h3>Students may work with tools/platforms such as</h3><div className="ignou-tag-list">{['Python', 'VS Code', 'HTML', 'CSS', 'JavaScript', 'SQL', 'MySQL / PostgreSQL', 'Excel', 'Power BI', 'Git', 'GitHub', 'ChatGPT', 'Copilot', 'HackerRank', 'W3Schools', 'SQLBolt', 'Kaggle', 'LinkedIn'].map((item) => <span key={item}>{item}</span>)}</div><small>Tools depend on the current AILYT track. These are not partnership claims.</small></div></div></section>
      <section className="ignou-section ignou-alt"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">WHY AILYT</p><h2>Structure That Keeps You Moving</h2></div><div className="ignou-reasons">{['Regular Mentor Support', 'Hands-On Computer Lab', 'Small Batches', 'Programming Practice', 'Live Projects', 'Industrial Training', 'GitHub Portfolio', 'Career Preparation'].map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3></article>)}</div></div></section>
      <section className="ignou-section ignou-glance"><div className="ignou-wrap"><div className="ignou-section-head"><p className="ignou-kicker">COURSE SUPPORT AT A GLANCE</p><h2>Know What the Track Includes</h2></div><div className="ignou-glance-grid">{[['Programs', 'IGNOU BCA + MCA Support'], ['Academic Support', 'Semester-Wise'], ['Programming Practice', 'Included'], ['Live Projects', 'Progressive'], ['Industrial Training', 'Included in Professional Track'], ['Assignment Guidance', 'Included'], ['PYQ Practice', 'Included'], ['Practical / Lab Support', 'Included where applicable'], ['Portfolio Development', 'Progressive'], ['Career Preparation', 'Included'], ['Location', 'AILYT Learning Centre, Dehradun'], ['Batch Details', 'Contact AILYT for current schedule']].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></div></section>
      <section className="ignou-section" id="faqs"><div className="ignou-wrap ignou-faq-wrap"><div className="ignou-section-head"><p className="ignou-kicker">CLEAR ANSWERS</p><h2>Frequently Asked Questions</h2></div>{faqs.map(([question, answer], index) => <div className={`ignou-faq ${openFaq === index ? 'is-open' : ''}`} key={question}><button type="button" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}><span>{question}</span><b>{openFaq === index ? '−' : '+'}</b></button>{openFaq === index && <p>{answer}</p>}</div>)}</div></section>
      <section className="ignou-final"><div className="ignou-wrap ignou-final-inner"><div><p className="ignou-kicker">START BUILDING ALONGSIDE YOUR DEGREE</p><h2>Ready to plan your IGNOU BCA/MCA learning journey?</h2><p>Book counselling to discuss your current semester, schedule, support needs, and the professional learning track.</p></div><div className="ignou-actions"><CTA onClick={openCounselling}>Book Free Counselling</CTA><CTA onClick={() => setModal('guide')} outline>Download Program Guide</CTA><a className="ignou-btn ignou-whatsapp" href={WHATSAPP_URL} target="_blank" rel="noreferrer">Chat on WhatsApp ↗</a></div></div></section>
      <p className="ignou-trust">IGNOU academic curriculum, examinations and degree requirements are governed by IGNOU. AILYT Learning Centre provides independent academic, practical, project, industrial training and career-development support for students.</p>
    </main>
    <div className="ignou-mobile-cta"><button type="button" onClick={openCounselling}>Counselling</button><a href={WHATSAPP_URL} target="_blank" rel="noreferrer">WhatsApp</a></div>
    {modal && <EnquiryModal type={modal} onClose={() => setModal(null)} />}
  </div>;
}

export default IgnouBcaMcaLanding;
